version: "2"
linters:
  default: none
  enable:
    - asasalint
    - dogsled
    - dupl
    - dupword
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - perfsprint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    funlen:
      lines: 100
      statements: 50
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G104
    govet:
      disable:
        - fieldalignment
        - nilness
      enable-all: true
    misspell:
      locale: US
    nolintlint:
      require-explanation: true # require an explanation for nolint directives
      require-specific: true # require nolint directives to be specific about which linter is being skipped
      allow-unused: false # report any unused nolint directives
    revive:
      confidence: 0

  exclusions:
    generated: lax
    presets:
      - std-error-handling

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/goyek/goyek/v2
