linters-settings:
  funlen:
    lines: 100
    statements: 50
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/goyek/goyek/v2
  govet:
    enable-all: true
    disable:
    - fieldalignment
    - nilness
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: false # require machine-readable nolint directives (with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: true # require nolint directives to be specific about which linter is being skipped
  revive:
    confidence: 0

linters:
  disable-all: true
  enable:
    - asasalint
    - dogsled
    - dupl
    - dupword
    - errcheck
    - exportloopref
    - funlen
    - gocritic
    - goconst
    - gocyclo
    - gofumpt
    - goimports
    - revive
    - godot
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - perfsprint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude:
    - EXC0001
