linters-settings:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/goyek/goyek
  govet:
    check-shadowing: true
  misspell:
    locale: US
    ignore-words:
      - importas
  nolintlint:
    allow-leading-space: false # require machine-readable nolint directives (with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  revive:
    confidence: 0

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - dogsled
    - errcheck
    - exportloopref
    - funlen
    - gochecknoinits
    - gocritic
    - goconst
    - gocyclo
    - gofumpt
    - goimports
    - revive
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  # enable issues excluded by default 
  exclude-use-default: false
