name: release

on:
  push:
    tags: [ 'v*' ]

jobs:
  godoc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - name: Update pkg.go.dev
        run: go get -u github.com/$GITHUB_REPOSITORY
