name: release

on:
  push:
    tags: [ 'v*' ]

jobs:
  godoc:
    runs-on: ubuntu-latest
    steps:
      - name: Wait 1 minute
        # make sure that new the tag is available for pkg.go.dev
        run: sleep 60
      - name: Update pkg.go.dev
        run: curl https://proxy.golang.org/github.com/${{ github.repository }}/@v/${{ github.ref_name }}.info
